server:
  servlet:
    context-path: /web-app
  port: 8081
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/librarydb"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: changeme
  profiles:
    active: local

integration:
  author:
    url:
      base: http://localhost:8081/author-app/author
      specific: ${integration.author.url.base}/{authorId}
